### ISSUE TITLE
Tracking result shows jump at the border between the uncalibrated camera pair

### ISSUE THREAD

**Issue by yhju** [dysonltd-zz/gts#4]
![yujin_tracking_result](https://f.cloud.github.com/assets/1287762/1304036/5cb7de0c-3172-11e3-8d44-ac6a518ab915.png)

Calibrated Pair
- Camera1 - Camera2
- Camera2 - Camera3
- Camera3 - Camera4

Uncalibrated Pair
- Camera4 - Camera1

**Comment by akramhussein** [comment]
This bug was addressed in commit [a919f06447b049eac8486d7097ac4dad2b2f75da](https://github.com/dysonltd/gts/commit/) and should now be resolved. If this is not the case, this bug can be re-opened and further investigated.

Please see images below which have been generated from the dataset you provided but re-tracked using v0.4.5.

**Track Robot Screenshot**
![trackrobotwidgetscreenshot](https://f.cloud.github.com/assets/586938/1314357/04b8b0ae-3272-11e3-96b1-8b35639a9b5a.png)

**Post Process Screenshot**
![postprocesswidgetscreenshot](https://f.cloud.github.com/assets/586938/1314355/04993be8-3272-11e3-9645-aca9c2ccabf8.png)

**Track Result Merge**
![track_result_img_out](https://f.cloud.github.com/assets/586938/1314356/04aaa2ca-3272-11e3-8f5c-0469191354bf.png)

**Track Result (All Positions)**
![track_result_img_raw](https://f.cloud.github.com/assets/586938/1314358/04b8dbf6-3272-11e3-9e1b-ed55dbceca67.png)

**Comment by yhju** [comment]
Thank you for fix the problem.
